services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: totaleconomy
    volumes:
      - ./totaleconomy-common/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql
